# Generated by Django 5.0.2 on 2024-06-06 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gecopf', '0004_alter_customuser_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='address',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='birth_date',
            new_name='fecha_de_nacimiento',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_picture',
            new_name='imagen_de_perfil',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_number',
            new_name='numero_de_telefono',
        ),
    ]
