# Generated by Django 5.0.2 on 2024-06-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gecopf', '0005_rename_address_customuser_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
