# Generated by Django 5.0.2 on 2024-06-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gecopf', '0007_customuser_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='imagen_de_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
