# Generated by Django 5.0.2 on 2024-06-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gecopf', '0011_alter_concept_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='tipo',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Gasto', 'Gasto'), ('Deuda', 'Deuda'), ('Ahorro', 'Ahorro')], help_text='Ingrese el tipo del concepto', max_length=10),
        ),
    ]
