# Generated by Django 5.0.2 on 2024-06-09 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gecopf', '0012_alter_concept_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
