# Generated by Django 5.0.2 on 2024-06-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gecopf', '0013_alter_transaction_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='categorias_preferidas',
            field=models.ManyToManyField(to='gecopf.categoria'),
        ),
        migrations.CreateModel(
            name='ConsejoFinanzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consejo', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categorias', models.ManyToManyField(to='gecopf.categoria')),
            ],
        ),
    ]
