# Generated by Django 5.0.2 on 2024-06-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gecopf', '0014_categoria_customuser_categorias_preferidas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Ingrese una breve descripción de la categoría', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='consejofinanzas',
            name='consejo',
            field=models.TextField(blank=True, help_text='Ingrese una breve descripción del consejo', max_length=500, null=True),
        ),
    ]
